language: node_js
node_js:
- '11'
cache:
  directories:
  - node_modules
install: npm install
script: npm test
before_deploy: echo 'All unit tests passed;
  Preparing to deploy Get a Library Card to AWS'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-library-card-app
  env: nypl-library-card-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-library-card-app-production
  on:
    repo: NYPL/nypl-library-card-app
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-library-card-app
  env: nypl-library-card-app-qa-3
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-library-card-app-qa-3
  on:
    repo: NYPL/nypl-library-card-app
    branch: qa
# Disabling development deploy for cost savings
# - provider: elasticbeanstalk
#  skip_cleanup: true
#  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
#  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
#  region: us-east-1
#  app: nypl-library-card-app
#  env: nypl-library-card-app-development
#  bucket_name: elasticbeanstalk-us-east-1-224280085904
#  bucket_path: nypl-library-card-app-development
#  on:
#    repo: NYPL/nypl-library-card-app
#    branch: master
after_deploy: echo 'Successfully executed deploy trigger for Get a Library Card on
  AWS'
env:
  global:
    secure: ZhfM2PS5VxJCdfIUQXwHUPuqgDMklKwFCSPK7qVcirOTmfvkV7LgA+QIiiB/g+1sxVtDwYId8H7qL7ckymJh4WstXzanyT2XkXmJ3d8NqVTgzMSZCmEsPEtmxow4xXQNadIljTIDN0iUp9NGQDrm3EN5Dd23hCttV/VzQzg1xlbdWK3RRBurwXefkqokgA8kawb4u/sjibCiXKgyz8nuscGHn4u9NSCdQNnIq600EmMnznDT8k5Tfojv29qz2+Vs6wEI8LCjZ+e9vYUDMTCAimVquVjDsMll+RgWPlpUasElFtalJybqGQhGgHspPDO7/yk882a9JRgk/iamXv7paKez+HoB1akZwVA7UDu3nZGfQuB/4mB6mN+ZzlZ/GjpVitvvFBu3ns/02DM6eVdCf8rCEm8JetydJ3Y0eIwjMKCN3VMxCyhYNzzvI3qCcK9emIxJOnQoSTUFB6xMAK/IDJs+2kVtzCzLUckjtWzWQFewN7Hz6Gq7sw6uK4TaEeMG495QY18VenXX+SJtyPVmQPhaABxnYjcwJCz1L5M2rUHrWDpXXIxndpefKudmXTFZ/RWU91YmNE87gWb0/fk2GauJLcXjYgr6rw+74R+MfVFTljqK9HB+x+8d0e9yZqo/c27IfnO90lUOvN2fx1uPS5sGLGxmNc+4ss3azubZIWg=
