language: node_js
services:
- docker
node_js:
  - "10"
branches:
  only:
  - qa
  - DOPS-554/terraform
cache:
  directories:
    - node_modules
install: npm install
script: npm test

jobs:
  include:
    - stage: docker build
      if: (branch = DOPS-554/terraform)
      env:
      - ENV=qa
      - ECR_URL=946183545209.dkr.ecr.us-east-1.amazonaws.com/nypl-library-card-app
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
      install:
        - pip install --user awscli
        - export LOCAL_TAG_NAME="${ENV}-latest"
      script:
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
        - DOCKER_BUILDKIT=1 docker build -t "$LOCAL_TAG_NAME" --secret id=AWS_ACCESS_KEY_ID --secret id=AWS_SECRET_ACCESS_KEY --build-arg RAILS_ENV="${ENV}" .
        - docker tag "$LOCAL_TAG_NAME" "$ECR_URL:$LOCAL_TAG_NAME"
        # Re-tag last latest image just in case
        - |
            MANIFEST=$(aws ecr batch-get-image --repository-name my-library-nyc-app --image-ids imageTag="$ENV-latest" --output json | jq --raw-output --join-output '.images[0].imageManifest')
            aws ecr batch-delete-image --repository-name my-library-nyc-app --image-ids imageTag="$ENV-previous" || true
            aws ecr put-image --repository-name my-library-nyc-app --image-tag "$ENV-previous" --image-manifest "$MANIFEST"
        - docker push "$ECR_URL:$LOCAL_TAG_NAME"

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-production-2
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-production
    on:
      repo: NYPL/nypl-library-card-app
      branch: production
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-qa-18
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-qa
    on:
      repo: NYPL/nypl-library-card-app
      branch: qa
after_deploy: echo "Successfully executed deploy trigger for Get a Library Card on AWS."
