language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install: npm install
script: npm test
before_deploy: echo "All unit tests passed; Preparing to deploy Get a Library Card to AWS."
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-production-2
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-production
    on:
      repo: NYPL/nypl-library-card-app
      branch: production
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-qa-18
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-qa
    on:
      repo: NYPL/nypl-library-card-app
      branch: qa
after_deploy: echo "Successfully executed deploy trigger for Get a Library Card on AWS."
env:
  global:
    - secure: "NeybcWJFnVy0G2wLB1ZsUqLkjl9SZdOPvGfe4HsEn+BV8V5rMfwebiTo7NxSTzNeywKp4abGemqQzI/RF0y/N/MsgYh3bMDIvVpKWl4XrHyNDcr6n/rhDnYlSHkIwGSQlhn1ThJ5lOzTxKCgfRLLuui+ny8ekLjfwIprIH7fxcXVxESBoqweylJBZFZEnfms1tUk9BehikJwvchx2RbGCiR0ozgHDSdYwoiQR9sKP+i8Gxf/dASVh0xxOPLxarNprURq+0P0uJGzhTO7mm++qBVIhYHVi0i1LSu7rDL7o4IJO35eQxvAiPh/D3XujWcecLMMbyyObPDZJnbcYAVGMWeHt7dKVyNLAI36e4Fl2PItrvB3QogMMF/WMauuhJHxXfGygmc632aofoOazbNp5sbMHB0NX5divcjRW4zGgLTh23Trce+3utAuSpGQmzUvpJvhCzCkNUnGijO2WSY+5WOE9SYOGOuMP0GOc2slUppfLhVU7sH7Q7XAtmxnA60lcCTvkeDJTEdsRZSZbPEw1yU8B00EPNMwgheHGgFFK6P6Ovv/1BbbtvV8JSIGhbWgQ5lnwbs+NuOpnW1g1Ov/gLf3J8uJR9WoBh/8i6SWyHO5vroHhW/YeFmIuITqNKnGlLzbGfSQF0RDngEZtldCTv2kYlysgqB4sb45+GnX8oc="
