language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install: npm install
script: npm test
before_deploy: echo "All unit tests passed; Preparing to deploy Get a Library Card to AWS."
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-production-2
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-production
    on:
      repo: NYPL/nypl-library-card-app
      branch: production
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-qa-18
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-qa
    on:
      repo: NYPL/nypl-library-card-app
      branch: qa
after_deploy: echo "Successfully executed deploy trigger for Get a Library Card on AWS."
env:
  global:
    - secure: GkM3jfBDIHZo1JuWurHYtzDif5ePAVnTO/BukCkjZL6+Pi/i1itDUI6NeCtgJLshtzWz6Ys5ZdOjxP+Ky35/i6TN3gCy8rKpcP/DY+OhefzMQSiA7IlmZbNLvVbXQVr17A2kr/5eP6aEP6vR5lApJ1wkC78Iw/PDry1m/WT/LhZojKOF2Akbfbqjtt1qRNErHVdlcb2OGQCmCwEowOZRpNpM8O+h0SHmcWyA0+TqCCS6czMANOpkyK1Gfl8zWrsSe8F3T1fNjEkFaxp/seFy+e1MUsl9IvN2NVl05k7CZTOOjptcMVzR0sqz2SUKUM5WADIWgdMBpOzXQRzgLzKnqm7+mWUCTAjZZZN1scL2ggCxxZn6kf6HZsjTDltPuYHzU+FJeqGzPisvKlVW8it6KfBbJvIgJP+R9JrI9foPfZbH5nrdkkQSlLZIMJT7FeyPizMSdSZ6lTxJhtXAefchBkSeDknUo0qdfFdjTpjbcvNtnt7WUVTAWVI2NrzgXWq9mVJ52pSft9ShbiJKi3KvsXBcfoWb0ZxmKetEZU0XblIhTmGi7oiFdtdodWGowpNfvSVQX9mSHGysNyz+sJSAX8BDmn6D5HASgc/l2RI91rSUReUMoyKzAQ9+BI1Zav+5fLGDNmvyA4xsSth/WaJQPUUy95nyiIsXq72ViN1MDrE=
    - secure: "rLyWPbjM6VMz7D0Onu7AjTdewKmdBfMgafMZhTeDZ70M+V3bfKIoTvPr5/ityN0bDlgxylhd6Nx3JKFfzpSztaev1NFizv2PlM/5/1oNXON1L4EbEa0oNEJDXKfpzD/7yKZf2CqBmE1m3PL6p0Hzqn0qobMJCrCE6PQzhtt7RsbBYN9sWvejFcVqpDlC8f56zhta9ULIkMA4W3KQi9ipNU6T9dULA3FESRcycDV9SIJc5xhtztm/Lk+7GxSnDeFUaBH3SGLxV4NTvVgucPd9VoSX4JfgXbrtJeX7vOjJaQ/7pZBQt3hBivSSyh+TID9qLTghvGrvirOuxqRPB6ua03kMQQgtTMwTOEde5nNxl0M6S9aZskS3uJKOsjYZbPnNDCYjO35WEZ4hfraqTkn8StGWUEveXiaeuLr7ptJcALfTvyycI3gNFYhz86RVpjBJc02yHN/zLhQ9hjVPK3/13j6n7HeqACLAJ7HPhZDV1GXTj/IcKq63sv07TEuz+ijlkUSx56vq1CuXXR7BmsBp2fJQWidrEnQsgtsK6etXK/fdnJjbTETMVrnmSgwLL5G1sOr1qJpTfxDpYDpsi21VrAdwj2Wc3Exfbr8q89vxLcjH6/dDmi04KdfOxnOaM1PgCFd5k66UES11hEEvkakp1Z4PjfcS8uxu8h/Goer/EJ8="
    - secure: "X445ZdQvmR9/zkmLpk5OFRCC4fwIbCw+BtPFNp+kqcuR6Ni4I0l12sg+1sMabUDUk4bQj85roeblYoJN3UjvnuiLiWky69+hk/Hv8fl5a07bSXvMv/PDKJ/orGONaKSIEMo10vZTZtgWNu2FnmPi+axx+xb4tOKiRB06hCLyP4KMKANv5/YlQHQ6ihXL1twO4GYc8jajzOnArcVAxN/CcWhSOwlJ/9XD87xWe6trnhWWQHRZZuSJjwUl57lfWVnGgZzEmS13wG7D9ezZMEqEbvsb/s+D/V2k6I2achocFLcTl5tzv9GE5NTPqvMTTXDLyU2JEKlCht2+9UiA9AwtiaEd6gkBhQOL1rs604ut9T/Z22RnrrZSdsu0SVvON2VzZ78jhhZNULiwJlcXkho4xsvBEjIxiqiMDxc1u5pyzVPv6TJ/aoqbPYP8JB4AqM2HaPX+vxZAqDh8I5VjMwlKyIQUScFxt4TfLW0/9xfXE4NWDYJ0W7pa6Jzcu0S44pvWCmbvTbsQkS6+M7RDE6dDvad30PGoWzHu0sMdUW/9tiluYQtXRQTHWECfncGDw0ig+ICGRhl3xzqY3i/ySAeJ58BqBQsinoN67dS1JpOC0S9DzaH8Ly+DeFnitERAVA0chjtQRk+4vNml2dgEHLZ0qJB5go1pKEvyGqsRG8qPPok="
    - secure: "fCsqZ4XHK45F+YKWTFL4aZGKt6GvDy99kjM7PM/k14sdEX5zGKqOuAJvsjiZv/co1iVSt6l1uxFE/0hCrYqook5D9UyVB+J9LdCtWuJeiorW0bjWxjqRMjVsAKxdgAzBbZZbOcy6+gi23+3QyfomQt/+oP5YimU7OAPgUCLGnvZnA17vPtP9vN6TvV0/mGn7qQuLyZh1+o1N33x19ss8/f751N5BfmLGtTSze/5FrzHlVk4/MyZQpn8+dpyzwwPDCbr+lh8nMWZauqdRvtm7gZ6gGzjE07OrrwVkil27+MfZhwE+mnVb0ANbA55iZ3O35Z3At3v9x2MKSrdtjFE6YiWrsgjOifn3wwVGiZ3UIT75kN3PEk/TxeSi/b5HTiihmt972Z564biC+IddoWaynKlJPaQXoJLC5NAV6w0gMYewHftfh/ZuG+gfiqpvNkL91OIlVJbW/q5MpqKYMDEMWj5eUMTtoKp6Q+HyO5EqMOdKgOfNmSi5ezH97sSIycBSfPASRozhaU6sobWlxeaOw5SzBRvI3flS6ysIUswiddMr/h/vdD98lzFE/WhuNiNeeEPLheeulU5GCQWEaNTPRXUZBEMq9RyYigNXlIr0r0/ZEMEbrVVAzFjsYRTwhxnFLhzQDELDnuofHi0oH+VesLylL1JASLpSfG80gibp6YI="
    - secure: "JevPcCkRqnpSCddTYjuQdH33fMMtmr8yO7ALfVBrV0Tzlgt0SQXTvWJYsKITXptnUmCs73gvZEsGUJVLQKuDu3zwCgHXmgyj2+kYA8BFP3asQnHMTHOGAsmjByD+0CJELI9RR4wIEsOIZTj6AJ9noz6nagRPDSI8KbS3auDMNHCYwzZNODGsF1hUxTEpwoKC9u+lF/mqg/aM4q2S3bl997n46FAeHXka/jODntZjySjWuHmPaRhBRGmVuUK4Xnw1yy5eT/v3n4S8AN7aDC3q7aL9Ozp8LBI3HDVQTbKMusZ5lOvh50SgYqAXkqMrEAE44P+dW2MAVQIQfHi5KR8lonKRy8vNyZtqj3hq+WnZ4/gwTD1EYPicbhOsANwkv0ESptWrfvM0wdN/j2S9X2YKe7Mf6ikDV5iFJIDYKedhzU/6MN/0ecXHZfEriDff7Ct67PJU8YqdIcoKj4UrAngX21hsMpBXCqiFN3XI4Ew6bl2ql+nGP0zWLHvb2chONMO1DS6Mr5iZTYnsMtjOEkaTD7ut4KRN7fPeWdt4yce/bPNdJe4abZCLkZBIIg6p5eJ1jWN9iWuhDs4SL1EC9u/rpgQqqWr6XG7hkN88TOLgm79lJq38dEtjuP55DhWhFGV6fe/sDvvLcAwdmdAPHRbBRW6NnbukDuhG6KCb61/nnAc="
