language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install: npm install
script: npm test
before_deploy: echo "All unit tests passed; Preparing to deploy Get a Library Card to AWS."
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-production-2
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-production
    on:
      repo: NYPL/nypl-library-card-app
      branch: production
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
    region: us-east-1
    app: nypl-library-card-app
    env: nypl-library-card-app-qa-18
    bucket_name: elasticbeanstalk-us-east-1-946183545209
    bucket_path: nypl-library-card-app-qa
    on:
      repo: NYPL/nypl-library-card-app
      branch: qa
after_deploy: echo "Successfully executed deploy trigger for Get a Library Card on AWS"
env:
  global:
    - secure: "rLyWPbjM6VMz7D0Onu7AjTdewKmdBfMgafMZhTeDZ70M+V3bfKIoTvPr5/ityN0bDlgxylhd6Nx3JKFfzpSztaev1NFizv2PlM/5/1oNXON1L4EbEa0oNEJDXKfpzD/7yKZf2CqBmE1m3PL6p0Hzqn0qobMJCrCE6PQzhtt7RsbBYN9sWvejFcVqpDlC8f56zhta9ULIkMA4W3KQi9ipNU6T9dULA3FESRcycDV9SIJc5xhtztm/Lk+7GxSnDeFUaBH3SGLxV4NTvVgucPd9VoSX4JfgXbrtJeX7vOjJaQ/7pZBQt3hBivSSyh+TID9qLTghvGrvirOuxqRPB6ua03kMQQgtTMwTOEde5nNxl0M6S9aZskS3uJKOsjYZbPnNDCYjO35WEZ4hfraqTkn8StGWUEveXiaeuLr7ptJcALfTvyycI3gNFYhz86RVpjBJc02yHN/zLhQ9hjVPK3/13j6n7HeqACLAJ7HPhZDV1GXTj/IcKq63sv07TEuz+ijlkUSx56vq1CuXXR7BmsBp2fJQWidrEnQsgtsK6etXK/fdnJjbTETMVrnmSgwLL5G1sOr1qJpTfxDpYDpsi21VrAdwj2Wc3Exfbr8q89vxLcjH6/dDmi04KdfOxnOaM1PgCFd5k66UES11hEEvkakp1Z4PjfcS8uxu8h/Goer/EJ8="
    - secure: "X445ZdQvmR9/zkmLpk5OFRCC4fwIbCw+BtPFNp+kqcuR6Ni4I0l12sg+1sMabUDUk4bQj85roeblYoJN3UjvnuiLiWky69+hk/Hv8fl5a07bSXvMv/PDKJ/orGONaKSIEMo10vZTZtgWNu2FnmPi+axx+xb4tOKiRB06hCLyP4KMKANv5/YlQHQ6ihXL1twO4GYc8jajzOnArcVAxN/CcWhSOwlJ/9XD87xWe6trnhWWQHRZZuSJjwUl57lfWVnGgZzEmS13wG7D9ezZMEqEbvsb/s+D/V2k6I2achocFLcTl5tzv9GE5NTPqvMTTXDLyU2JEKlCht2+9UiA9AwtiaEd6gkBhQOL1rs604ut9T/Z22RnrrZSdsu0SVvON2VzZ78jhhZNULiwJlcXkho4xsvBEjIxiqiMDxc1u5pyzVPv6TJ/aoqbPYP8JB4AqM2HaPX+vxZAqDh8I5VjMwlKyIQUScFxt4TfLW0/9xfXE4NWDYJ0W7pa6Jzcu0S44pvWCmbvTbsQkS6+M7RDE6dDvad30PGoWzHu0sMdUW/9tiluYQtXRQTHWECfncGDw0ig+ICGRhl3xzqY3i/ySAeJ58BqBQsinoN67dS1JpOC0S9DzaH8Ly+DeFnitERAVA0chjtQRk+4vNml2dgEHLZ0qJB5go1pKEvyGqsRG8qPPok="
