name: Playwright Tests

on:
  push:
    branches: [main, swis-121/debug-verification-address-bug]
  pull_request:
  workflow_call:

env:
  NODE_ENV: development
  NEW_RELIC_ENABLED: false
  PATRON_CREATION_URL: ${{ vars.PATRON_CREATION_URL_QA }}
  PATRON_VALIDATION_URL: ${{ vars.PATRON_VALIDATION_URL_QA }}
  OAUTH_PROVIDER_URL: ${{ vars.OAUTH_PROVIDER_URL }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  IPSTACK_KEY: ${{ secrets.IPSTACK_KEY }}

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Verify Secrets and Create .env file
        run: |
          echo "Verifying that secrets are available..."
          if [ -n "$OAUTH_CLIENT_ID" ]; then echo "OAUTH_CLIENT_ID is set."; else echo "OAUTH_CLIENT_ID is NOT set or is empty."; fi
          if [ -n "$OAUTH_CLIENT_SECRET" ]; then echo "OAUTH_CLIENT_SECRET is set."; else echo "OAUTH_CLIENT_SECRET is NOT set or is empty."; fi
          if [ -n "$IPSTACK_KEY" ]; then echo "IPSTACK_KEY is set."; else echo "IPSTACK_KEY is NOT set or is empty."; fi

          echo "---"
          echo "Creating .env.local.debug file"
          
          echo "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}" >> .env.local.debug
          echo "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}" >> .env.local.debug
          echo "IPSTACK_KEY=${IPSTACK_KEY}" >> .env.local.debug
          echo "PATRON_CREATION_URL=${PATRON_CREATION_URL}" >> .env.local.debug
          echo "PATRON_VALIDATION_URL=${PATRON_VALIDATION_URL}" >> .env.local.debug
          echo "OAUTH_PROVIDER_URL=${OAUTH_PROVIDER_URL}" >> .env.local.debug

          echo ".env.local.debug file created successfully."

          # This command prints the file content but masks the values for security
          awk -F= '{print $1"=***"}' .env.local.debug

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright reports on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
