name: 'Master Branch Regression Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  ubuntu-job:
    name: 'Test on Ubuntu'
    runs-on: ubuntu-latest
    env: 
        NODE_ENV: test
        SELENIUM_HUB_HOST: hub
        TEST_HOST: testHost
    steps:
      # The next 3 steps are for building the web application to be tested and starting the web server on the runner environment
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      - name: Run apt update
        run: sudo apt update
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.19'
      - name: NPM Install
        run: npm install
      - name: NPM Test
        run: npm test
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
